/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chessapp;

import Model.GameAnalysis;
import Model.GamesFromPgn;
import Model.LichessAPI;
import Model.OpeningHistogram;
import ModelView.GamesController;
import View.AuthView;
import View.ChessBoard1;
import View.ChessResourcesView;
import com.github.bhlangonijr.chesslib.Board;
import com.github.bhlangonijr.chesslib.game.Game;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.io.IOException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import org.jfree.chart.ChartPanel;
import View.ExercisesView;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author adria_6
 */
public class ChessAnalystHome extends javax.swing.JFrame {

    /**
     * Creates new form ChessAnalystHome
     */
    public ChessAnalystHome() {
        initComponents();
//        javax.swing.GroupLayout BoardLayout = new javax.swing.GroupLayout(boardUI);
//        boardUI.setLayout(BoardLayout);
//        BoardLayout.setHorizontalGroup(
//            BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 400, Short.MAX_VALUE)
//        );
//        BoardLayout.setVerticalGroup(
//            BoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 400, Short.MAX_VALUE)
//        );
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addComponent(boardUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                )
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addComponent(boardUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                )
//        );
//        getContentPane().add(boardUI);
//        boardUI.setVisible(true);
//        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgnFileChooser = new javax.swing.JFileChooser();
        GeneralPanel = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        loadPgnPanel = new javax.swing.JPanel();
        loadPgn = new javax.swing.JButton();
        practiceButton = new javax.swing.JButton();
        lichessTabButton = new javax.swing.JButton();
        resourcesButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        selectAnalysis = new javax.swing.JPanel();
        selectGameButton = new javax.swing.JButton();
        statisticsButton = new javax.swing.JButton();
        selectGame = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gamesList = new javax.swing.JList<>();
        listSelectButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        analysisPanel = new javax.swing.JPanel();
        boardHolderPanel = new javax.swing.JPanel();
        subpanel1 = new javax.swing.JPanel();
        selectFunctionButtonsPanel = new javax.swing.JPanel();
        tactOptsButton = new javax.swing.JButton();
        backSubpanel12 = new javax.swing.JButton();
        tactOpsListPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tactOptsList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        displayTactOptButton = new javax.swing.JButton();
        backSubpanel1 = new javax.swing.JButton();
        subpanel2 = new javax.swing.JPanel();
        backforwarButtonsPanel = new javax.swing.JPanel();
        movementButtonsPanel = new javax.swing.JPanel();
        boardPositionBackButton = new javax.swing.JButton();
        boardPositionForwardButton = new javax.swing.JButton();
        askBestMovePanel = new javax.swing.JPanel();
        userMoveField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bestMoveLabel = new javax.swing.JLabel();
        sideLabel = new javax.swing.JLabel();
        statisticsPanel = new javax.swing.JPanel();
        chartHolderPanel = new javax.swing.JPanel();
        backSelectAnalysisButton = new javax.swing.JButton();
        setUserLichessPanel = new javax.swing.JPanel();
        usernameLichessField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lichessUsernameButton = new javax.swing.JButton();

        pgnFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgnFileChooserActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(213, 249, 222));

        GeneralPanel.setBackground(new java.awt.Color(213, 249, 222));

        header.setBackground(new java.awt.Color(219, 244, 167));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/small_logo (3).png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 162, 172));
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        mainPanel.setLayout(new java.awt.CardLayout());

        loadPgnPanel.setBackground(new java.awt.Color(213, 249, 222));
        loadPgnPanel.setPreferredSize(new java.awt.Dimension(900, 700));

        loadPgn.setBackground(new java.awt.Color(0, 148, 76));
        loadPgn.setText("Cargar archivo pgn");
        loadPgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadPgnActionPerformed(evt);
            }
        });

        practiceButton.setBackground(new java.awt.Color(0, 148, 76));
        practiceButton.setText("Ejercicios de Practica");
        practiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                practiceButtonActionPerformed(evt);
            }
        });

        lichessTabButton.setBackground(new java.awt.Color(0, 148, 76));
        lichessTabButton.setText("Cargar juegos desde Lichess.org");
        lichessTabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lichessTabButtonActionPerformed(evt);
            }
        });

        resourcesButton.setBackground(new java.awt.Color(0, 148, 76));
        resourcesButton.setText("Recursos de Aprendizaje");
        resourcesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Menu Principal");

        javax.swing.GroupLayout loadPgnPanelLayout = new javax.swing.GroupLayout(loadPgnPanel);
        loadPgnPanel.setLayout(loadPgnPanelLayout);
        loadPgnPanelLayout.setHorizontalGroup(
            loadPgnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadPgnPanelLayout.createSequentialGroup()
                .addGap(379, 379, 379)
                .addGroup(loadPgnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lichessTabButton)
                    .addComponent(loadPgn)
                    .addComponent(practiceButton)
                    .addComponent(resourcesButton)
                    .addComponent(jLabel6)))
        );
        loadPgnPanelLayout.setVerticalGroup(
            loadPgnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadPgnPanelLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabel6)
                .addGap(54, 54, 54)
                .addComponent(lichessTabButton)
                .addGap(6, 6, 6)
                .addComponent(loadPgn)
                .addGap(6, 6, 6)
                .addComponent(practiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resourcesButton)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        mainPanel.add(loadPgnPanel, "card4");

        selectAnalysis.setBackground(new java.awt.Color(213, 249, 222));
        selectAnalysis.setPreferredSize(new java.awt.Dimension(900, 700));

        selectGameButton.setBackground(new java.awt.Color(0, 148, 76));
        selectGameButton.setText("Analizar un juego");
        selectGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectGameButtonActionPerformed(evt);
            }
        });

        statisticsButton.setBackground(new java.awt.Color(0, 148, 76));
        statisticsButton.setText("Estadísticas");
        statisticsButton.setAlignmentY(0.0F);
        statisticsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectAnalysisLayout = new javax.swing.GroupLayout(selectAnalysis);
        selectAnalysis.setLayout(selectAnalysisLayout);
        selectAnalysisLayout.setHorizontalGroup(
            selectAnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectAnalysisLayout.createSequentialGroup()
                .addContainerGap(470, Short.MAX_VALUE)
                .addGroup(selectAnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(selectGameButton)
                    .addComponent(statisticsButton))
                .addGap(394, 394, 394))
        );
        selectAnalysisLayout.setVerticalGroup(
            selectAnalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectAnalysisLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(selectGameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statisticsButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(selectAnalysis, "selectAnalysis");

        selectGame.setBackground(new java.awt.Color(213, 249, 222));
        selectGame.setPreferredSize(new java.awt.Dimension(900, 700));

        gamesList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gamesListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gamesList);

        listSelectButton.setBackground(new java.awt.Color(0, 148, 76));
        listSelectButton.setText("Analizar!");
        listSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSelectButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione un juego");

        javax.swing.GroupLayout selectGameLayout = new javax.swing.GroupLayout(selectGame);
        selectGame.setLayout(selectGameLayout);
        selectGameLayout.setHorizontalGroup(
            selectGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectGameLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(selectGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listSelectButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        selectGameLayout.setVerticalGroup(
            selectGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectGameLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listSelectButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(selectGame, "selectGame");

        analysisPanel.setBackground(new java.awt.Color(213, 249, 222));
        analysisPanel.setPreferredSize(new java.awt.Dimension(900, 700));

        boardHolderPanel.setBackground(new java.awt.Color(213, 249, 222));
        boardHolderPanel.setMaximumSize(new java.awt.Dimension(300, 300));
        boardHolderPanel.setPreferredSize(new java.awt.Dimension(300, 300));
        boardHolderPanel.setLayout(new java.awt.BorderLayout());

        subpanel1.setBackground(new java.awt.Color(0, 0, 255));
        subpanel1.setPreferredSize(new java.awt.Dimension(510, 400));
        subpanel1.setLayout(new java.awt.CardLayout());

        selectFunctionButtonsPanel.setBackground(new java.awt.Color(213, 249, 222));
        selectFunctionButtonsPanel.setPreferredSize(new java.awt.Dimension(900, 700));

        tactOptsButton.setBackground(new java.awt.Color(0, 148, 76));
        tactOptsButton.setText("Ver oportunidades tácticas");
        tactOptsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tactOptsButtonActionPerformed(evt);
            }
        });

        backSubpanel12.setBackground(new java.awt.Color(0, 148, 76));
        backSubpanel12.setText("Volver");
        backSubpanel12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSubpanel12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectFunctionButtonsPanelLayout = new javax.swing.GroupLayout(selectFunctionButtonsPanel);
        selectFunctionButtonsPanel.setLayout(selectFunctionButtonsPanelLayout);
        selectFunctionButtonsPanelLayout.setHorizontalGroup(
            selectFunctionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectFunctionButtonsPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(selectFunctionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tactOptsButton)
                    .addComponent(backSubpanel12))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        selectFunctionButtonsPanelLayout.setVerticalGroup(
            selectFunctionButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectFunctionButtonsPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(tactOptsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backSubpanel12)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        subpanel1.add(selectFunctionButtonsPanel, "first");

        tactOpsListPanel.setBackground(new java.awt.Color(219, 244, 167));

        jScrollPane2.setViewportView(tactOptsList);

        jLabel2.setText("Oportunidades tácticas");

        displayTactOptButton.setBackground(new java.awt.Color(0, 148, 76));
        displayTactOptButton.setText("Solucionar!");
        displayTactOptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayTactOptButtonActionPerformed(evt);
            }
        });

        backSubpanel1.setBackground(new java.awt.Color(0, 148, 76));
        backSubpanel1.setText("Volver");
        backSubpanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSubpanel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tactOpsListPanelLayout = new javax.swing.GroupLayout(tactOpsListPanel);
        tactOpsListPanel.setLayout(tactOpsListPanelLayout);
        tactOpsListPanelLayout.setHorizontalGroup(
            tactOpsListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tactOpsListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tactOpsListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayTactOptButton)
                    .addComponent(backSubpanel1)
                    .addComponent(jLabel2))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        tactOpsListPanelLayout.setVerticalGroup(
            tactOpsListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tactOpsListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayTactOptButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(backSubpanel1)
                .addGap(19, 19, 19))
        );

        subpanel1.add(tactOpsListPanel, "tactOpsListPanel");

        subpanel2.setLayout(new java.awt.CardLayout());

        backforwarButtonsPanel.setBackground(new java.awt.Color(219, 244, 167));
        backforwarButtonsPanel.setLayout(new java.awt.CardLayout());

        movementButtonsPanel.setBackground(new java.awt.Color(219, 244, 167));

        boardPositionBackButton.setText("<html>&#8592;");
        boardPositionBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardPositionBackButtonActionPerformed(evt);
            }
        });

        boardPositionForwardButton.setText("<html>&#8594;");
        boardPositionForwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardPositionForwardButtonActionPerformed(evt);
            }
        });
        boardPositionForwardButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boardPositionForwardButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout movementButtonsPanelLayout = new javax.swing.GroupLayout(movementButtonsPanel);
        movementButtonsPanel.setLayout(movementButtonsPanelLayout);
        movementButtonsPanelLayout.setHorizontalGroup(
            movementButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movementButtonsPanelLayout.createSequentialGroup()
                .addContainerGap(703, Short.MAX_VALUE)
                .addComponent(boardPositionBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(boardPositionForwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        movementButtonsPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {boardPositionBackButton, boardPositionForwardButton});

        movementButtonsPanelLayout.setVerticalGroup(
            movementButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movementButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movementButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boardPositionForwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boardPositionBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(253, Short.MAX_VALUE))
        );

        movementButtonsPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {boardPositionBackButton, boardPositionForwardButton});

        backforwarButtonsPanel.add(movementButtonsPanel, "card2");

        askBestMovePanel.setBackground(new java.awt.Color(219, 244, 167));

        userMoveField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMoveFieldActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 148, 76));
        jButton2.setText("Ingresar movimiento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("¿Cual es el mejor movimiento en esta posición?");

        javax.swing.GroupLayout askBestMovePanelLayout = new javax.swing.GroupLayout(askBestMovePanel);
        askBestMovePanel.setLayout(askBestMovePanelLayout);
        askBestMovePanelLayout.setHorizontalGroup(
            askBestMovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(askBestMovePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(askBestMovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bestMoveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(askBestMovePanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userMoveField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        askBestMovePanelLayout.setVerticalGroup(
            askBestMovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(askBestMovePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(askBestMovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(userMoveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bestMoveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        backforwarButtonsPanel.add(askBestMovePanel, "card3");

        subpanel2.add(backforwarButtonsPanel, "card2");

        javax.swing.GroupLayout analysisPanelLayout = new javax.swing.GroupLayout(analysisPanel);
        analysisPanel.setLayout(analysisPanelLayout);
        analysisPanelLayout.setHorizontalGroup(
            analysisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, analysisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(analysisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(subpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(analysisPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(subpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addGroup(analysisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(sideLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boardHolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        analysisPanelLayout.setVerticalGroup(
            analysisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(analysisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(analysisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subpanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(analysisPanelLayout.createSequentialGroup()
                        .addComponent(boardHolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(sideLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subpanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(analysisPanel, "analysisPanel");

        statisticsPanel.setBackground(new java.awt.Color(213, 249, 222));

        chartHolderPanel.setMaximumSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout chartHolderPanelLayout = new javax.swing.GroupLayout(chartHolderPanel);
        chartHolderPanel.setLayout(chartHolderPanelLayout);
        chartHolderPanelLayout.setHorizontalGroup(
            chartHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chartHolderPanelLayout.setVerticalGroup(
            chartHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );

        backSelectAnalysisButton.setBackground(new java.awt.Color(0, 148, 76));
        backSelectAnalysisButton.setText("Volver");
        backSelectAnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backSelectAnalysisButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statisticsPanelLayout = new javax.swing.GroupLayout(statisticsPanel);
        statisticsPanel.setLayout(statisticsPanelLayout);
        statisticsPanelLayout.setHorizontalGroup(
            statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chartHolderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(statisticsPanelLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(backSelectAnalysisButton)
                .addContainerGap(761, Short.MAX_VALUE))
        );
        statisticsPanelLayout.setVerticalGroup(
            statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsPanelLayout.createSequentialGroup()
                .addComponent(chartHolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backSelectAnalysisButton)
                .addGap(0, 279, Short.MAX_VALUE))
        );

        mainPanel.add(statisticsPanel, "statistics");

        setUserLichessPanel.setBackground(new java.awt.Color(213, 249, 222));

        usernameLichessField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameLichessFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre de usuario de Lichess.org");

        lichessUsernameButton.setBackground(new java.awt.Color(0, 148, 76));
        lichessUsernameButton.setText("Cargar Juegos");
        lichessUsernameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lichessUsernameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout setUserLichessPanelLayout = new javax.swing.GroupLayout(setUserLichessPanel);
        setUserLichessPanel.setLayout(setUserLichessPanelLayout);
        setUserLichessPanelLayout.setHorizontalGroup(
            setUserLichessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setUserLichessPanelLayout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addGroup(setUserLichessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(usernameLichessField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lichessUsernameButton))
                .addGap(424, 424, 424))
        );

        setUserLichessPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lichessUsernameButton, usernameLichessField});

        setUserLichessPanelLayout.setVerticalGroup(
            setUserLichessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setUserLichessPanelLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLichessField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lichessUsernameButton)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        mainPanel.add(setUserLichessPanel, "lichess");

        javax.swing.GroupLayout GeneralPanelLayout = new javax.swing.GroupLayout(GeneralPanel);
        GeneralPanel.setLayout(GeneralPanelLayout);
        GeneralPanelLayout.setHorizontalGroup(
            GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
            .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GeneralPanelLayout.setVerticalGroup(
            GeneralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralPanelLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(GeneralPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeneralPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gamesListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gamesListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gamesListMouseClicked

    private void selectGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectGameButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "selectGame");
    }//GEN-LAST:event_selectGameButtonActionPerformed

    private void loadPgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadPgnActionPerformed
        int returnValue = pgnFileChooser.showOpenDialog(this);
        String pathToPgn = "";
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = pgnFileChooser.getSelectedFile();
            pathToPgn = selectedFile.getAbsolutePath();
        } else {
            System.out.println("No file selected.");
        }

        gamesHolder = new GamesFromPgn(pathToPgn);
        gamesList.setListData(gamesHolder.getHeaderGameMap().keySet().toArray(String[]::new));
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "selectAnalysis");
    }//GEN-LAST:event_loadPgnActionPerformed

    private void listSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSelectButtonActionPerformed
        //Seleccionamos el juego que el usuario escogió en la lista
        Game game = gamesHolder.getHeaderGameMap().get(gamesList.getSelectedValue());
        
        //Ejecutamos el análisis del juego
        gameAnalysis = new GameAnalysis(game);
        try {
            gameAnalysis.makeEvaluations();
        } catch (IOException ex) {
            Logger.getLogger(ChessAnalystHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(ChessAnalystHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //Definimos la lista de fen para mostrar en el tablero
        fenToDisplay = gameAnalysis.getFenList();
        
        //Mostramos la posición inicial
        boardUI = new ChessBoard1(fenToDisplay.get(0));
        currentFenIndex = 0;
        
        boardHolderPanel.add(boardUI);
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "analysisPanel");
        pack();
    }//GEN-LAST:event_listSelectButtonActionPerformed

    private void boardPositionForwardButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boardPositionForwardButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_boardPositionForwardButtonKeyPressed

    private void boardPositionForwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardPositionForwardButtonActionPerformed
        if(currentFenIndex<fenToDisplay.size()-1){
            currentFenIndex++;
            boardHolderPanel.removeAll();
            boardUI = new ChessBoard1(fenToDisplay.get(currentFenIndex));
            boardHolderPanel.add(boardUI);
            boardHolderPanel.revalidate();
            boardHolderPanel.repaint();
        }
    }//GEN-LAST:event_boardPositionForwardButtonActionPerformed

    private void boardPositionBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardPositionBackButtonActionPerformed
        if(currentFenIndex>0){
            currentFenIndex--;
            boardHolderPanel.removeAll();
            boardUI = new ChessBoard1(fenToDisplay.get(currentFenIndex));
            boardHolderPanel.add(boardUI);
            boardHolderPanel.revalidate();
            boardHolderPanel.repaint();
        }
    }//GEN-LAST:event_boardPositionBackButtonActionPerformed

    private void tactOptsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tactOptsButtonActionPerformed
        gameAnalysis.makeTactOps("Ades1000");
        
        //We fill the tactOptsList table        
        tactOptsList.setListData(gameAnalysis.getTactOps().keySet().toArray(String[]::new));
        
        CardLayout card = (CardLayout)subpanel1.getLayout();
        card.show(subpanel1, "tactOpsListPanel");
    }//GEN-LAST:event_tactOptsButtonActionPerformed

    private void backSubpanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSubpanel1ActionPerformed
        CardLayout card = (CardLayout)subpanel1.getLayout();
        card.show(subpanel1, "first");
    }//GEN-LAST:event_backSubpanel1ActionPerformed

    private void displayTactOptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayTactOptButtonActionPerformed
        fenTactOptDisplayed = gameAnalysis.getTactOps().get(tactOptsList.getSelectedValue());
        System.out.println(fenTactOptDisplayed);
        String fen = fenTactOptDisplayed;
        
        boardHolderPanel.removeAll();
        boardUI = new ChessBoard1(fen);
        sideLabel.setText("Juegan :" + boardUI.getSide());
        boardHolderPanel.add(boardUI);
        boardHolderPanel.revalidate();
        boardHolderPanel.repaint();
        
        CardLayout card = (CardLayout)backforwarButtonsPanel.getLayout();
        card.show(backforwarButtonsPanel, "card3");
    }//GEN-LAST:event_displayTactOptButtonActionPerformed

    private void backSubpanel12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSubpanel12ActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "selectGame");
    }//GEN-LAST:event_backSubpanel12ActionPerformed

    private void statisticsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsButtonActionPerformed
        try {
            OpeningHistogram opHistogram = new OpeningHistogram(gamesHolder.getGames());
            
            ChartPanel myChart = new ChartPanel(opHistogram.getChart());
            myChart.setSize(640, 400);
            //myChart.setMouseWheelEnabled(true);
            chartHolderPanel.setLayout(new java.awt.BorderLayout());
            chartHolderPanel.add(myChart,BorderLayout.CENTER);
            chartHolderPanel.setPreferredSize(new Dimension(640, 480));
            chartHolderPanel.validate();
            
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "statistics");
            
        } catch (IOException ex) {
            Logger.getLogger(ChessAnalystHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_statisticsButtonActionPerformed

    private void backSelectAnalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSelectAnalysisButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "selectAnalysis");
    }//GEN-LAST:event_backSelectAnalysisButtonActionPerformed

    private void practiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_practiceButtonActionPerformed
        SwingUtilities.invokeLater(()-> new ExercisesView());
    }//GEN-LAST:event_practiceButtonActionPerformed

    private void usernameLichessFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameLichessFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameLichessFieldActionPerformed

    private void lichessUsernameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lichessUsernameButtonActionPerformed
        String user = usernameLichessField.getText();
        gamesHolder = new GamesFromPgn(GamesController.instanceGames(user));
        gamesList.setListData(gamesHolder.getHeaderGameMap().keySet().toArray(String[]::new));
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "selectAnalysis");
    }//GEN-LAST:event_lichessUsernameButtonActionPerformed

    private void lichessTabButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lichessTabButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "lichess");
    }//GEN-LAST:event_lichessTabButtonActionPerformed

    private void pgnFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgnFileChooserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgnFileChooserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card4");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void userMoveFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMoveFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userMoveFieldActionPerformed

    private void resourcesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesButtonActionPerformed
        SwingUtilities.invokeLater(()-> new ChessResourcesView());
    }//GEN-LAST:event_resourcesButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String userMove = userMoveField.getText();
        System.out.println(fenTactOptDisplayed);
        System.out.println(gameAnalysis.getBestMoves().keySet().contains(fenTactOptDisplayed));
        String bestMove = gameAnalysis.getBestMoves().get(fenTactOptDisplayed);
        String message = null;
        if(userMove.equals(bestMove)){
            message = "¡Correcto! El mejor movimiento es " + bestMove;
        } else {
            message = "Incorrecto. El mejor movimiento es " + bestMove;
        }
        bestMoveLabel.setText(message);
        bestMoveLabel.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChessAnalystHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChessAnalystHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChessAnalystHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChessAnalystHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ChessAnalystHome().setVisible(true);
                  new AuthView().setVisible(true);
            }
        });
    }

    private ChessBoard1 boardUI = new ChessBoard1("rn2k2r/ppp2ppp/8/3p4/6nq/4P2R/PPPPN1K1/RNBQ4 b kq - 1 12");
    private GamesFromPgn gamesHolder;
    private List<String> fenToDisplay;
    private int currentFenIndex;
    private GameAnalysis gameAnalysis;
    private String fenTactOptDisplayed;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GeneralPanel;
    private javax.swing.JPanel analysisPanel;
    private javax.swing.JPanel askBestMovePanel;
    private javax.swing.JButton backSelectAnalysisButton;
    private javax.swing.JButton backSubpanel1;
    private javax.swing.JButton backSubpanel12;
    private javax.swing.JPanel backforwarButtonsPanel;
    private javax.swing.JLabel bestMoveLabel;
    private javax.swing.JPanel boardHolderPanel;
    private javax.swing.JButton boardPositionBackButton;
    private javax.swing.JButton boardPositionForwardButton;
    private javax.swing.JPanel chartHolderPanel;
    private javax.swing.JButton displayTactOptButton;
    private javax.swing.JList<String> gamesList;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton lichessTabButton;
    private javax.swing.JButton lichessUsernameButton;
    private javax.swing.JButton listSelectButton;
    private javax.swing.JButton loadPgn;
    private javax.swing.JPanel loadPgnPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel movementButtonsPanel;
    private javax.swing.JFileChooser pgnFileChooser;
    private javax.swing.JButton practiceButton;
    private javax.swing.JButton resourcesButton;
    private javax.swing.JPanel selectAnalysis;
    private javax.swing.JPanel selectFunctionButtonsPanel;
    private javax.swing.JPanel selectGame;
    private javax.swing.JButton selectGameButton;
    private javax.swing.JPanel setUserLichessPanel;
    private javax.swing.JLabel sideLabel;
    private javax.swing.JButton statisticsButton;
    private javax.swing.JPanel statisticsPanel;
    private javax.swing.JPanel subpanel1;
    private javax.swing.JPanel subpanel2;
    private javax.swing.JPanel tactOpsListPanel;
    private javax.swing.JButton tactOptsButton;
    private javax.swing.JList<String> tactOptsList;
    private javax.swing.JTextField userMoveField;
    private javax.swing.JTextField usernameLichessField;
    // End of variables declaration//GEN-END:variables
}
